### PR TITLE
adding my git notes

### PR DESCRIPTION
**Pull request by cbm755**

### CODE REVIEW

**Comment by cbm755** [comment]
pls merge!!!!!1111!one!

**Comment by sunxd3** [comment]
+1

**Review by Julian-Mentasti — APPROVED** [review]
looks like a readme

**Review by hanrach — COMMENTED** [review]
+1

**Comment by lchar** [comment]
Bring your own towel!

**Comment by patrickwalls** [comment]
Thanks for your contribution!

**Pull request merged**
